#!/usr/bin/env python3
"""Index of docs/DECISIONS.md, so a session can find what is current without
reading 400KB, and so two branches can't both take the same ID.

    python3 tools/decisions_index.py          write docs/DECISIONS_INDEX.md
    python3 tools/decisions_index.py --check  exit 1 if the index is out of date
    python3 tools/decisions_index.py --next   print the next free ID

A decision is a `## D### — Title` heading with a `- **Status:** …` line near the
top. "Superseded by" is read from a "superseded by D###" or "replaced by D###"
note in the first lines of the record. No dependencies beyond Python 3.9.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECISIONS = ROOT / 'docs' / 'DECISIONS.md'
INDEX = ROOT / 'docs' / 'DECISIONS_INDEX.md'
HEADING = re.compile(r'^## (D\d{3,}) — (.+)$')
SUPERSEDED = re.compile(r'(?:[Ss]uperseded|[Rr]eplaced)( in part| in whole| for new runs)? by ((?:D\d{3}(?:[, ]+(?:and )?)?)+)')
LINK = re.compile(r'\[([^\]]+)\]\([^)]*\)')
LOOKAHEAD = 14


def parse(text=None):
    """Every decision as (id, title, status, superseded_by), in file order."""
    lines = (DECISIONS.read_text() if text is None else text).split('\n')
    found = []
    for number, line in enumerate(lines):
        match = HEADING.match(line)
        if not match:
            continue
        head = lines[number + 1:number + 1 + LOOKAHEAD]
        status = next((entry for entry in head if '**Status:**' in entry), '')
        status = LINK.sub(r'\1', status.split('**Status:**', 1)[-1].strip()) if status else ''
        status = re.split(r'(?<=[a-z0-9)])\.(?:\s|$)|:\s|\s\(', status, maxsplit=1)[0].strip()[:90]
        by = SUPERSEDED.search(LINK.sub(r'\1', ' '.join(lines[number:number + 1 + LOOKAHEAD])))
        found.append((match.group(1), match.group(2).strip(), status,
                      ' '.join(re.findall(r'D\d{3}', by.group(2))) + (' (' + by.group(1).strip().replace('in ', 'in ') + ')' if by.group(1) in (' in part', ' for new runs') else '') if by else ''))
    return found


def next_id(decisions):
    return 'D%03d' % (max(int(entry[0][1:]) for entry in decisions) + 1)


def render(decisions):
    rows = ['| ID | Title | Status | Superseded by |', '|---|---|---|---|']
    for ident, title, status, by in decisions:
        rows.append(f'| [{ident}](DECISIONS.md#{ident.lower()}--{slug(title)}) | {title.replace("|", "/")} | {status.replace("|", "/")} | {by} |')
    return '\n'.join([
        '# Decision index',
        '',
        '**Generated by `python3 tools/decisions_index.py` from [DECISIONS.md](DECISIONS.md). Do not edit it by hand: add or change a decision, then regenerate** (a test fails if it is out of date, and if two branches took the same ID). '
        f'The next free ID is **{next_id(decisions)}** (`python3 tools/decisions_index.py --next` prints it).',
        '',
        'To read a decision, grep its heading: `grep -n "^## D004" docs/DECISIONS.md`. Never read DECISIONS.md whole.',
        '',
        *rows, ''])


def slug(title):
    """GitHub's anchor for a heading's title: lower case, punctuation dropped, spaces to hyphens."""
    return re.sub(r'\s', '-', re.sub(r'[^\w\s-]', '', title.lower()))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='exit 1 if docs/DECISIONS_INDEX.md is out of date')
    parser.add_argument('--next', action='store_true', help='print the next free decision ID')
    args = parser.parse_args()
    decisions = parse()
    if args.next:
        print(next_id(decisions))
        return 0
    text = render(decisions)
    if args.check:
        current = INDEX.read_text() if INDEX.exists() else ''
        if current != text:
            print('docs/DECISIONS_INDEX.md is out of date: run python3 tools/decisions_index.py', file=sys.stderr)
            return 1
        return 0
    INDEX.write_text(text)
    print(f'Wrote {INDEX.relative_to(ROOT)}: {len(decisions)} decisions, next free ID {next_id(decisions)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
