#!/usr/bin/env node
// Builds data/tower/enemies.json: The Tower's Tier 1 enemies, wave by wave,
// from TheTowerSDK (MIT licence, by TmRxJD). Never edit the JSON by hand;
// change this script and rerun it.
//
//     npm pack thetowersdk@0.11.0 && tar xzf thetowersdk-0.11.0.tgz
//     (cd package && npm install --omit=dev)
//     node tools/import_tower_enemies.mjs package
//
// What comes from where:
// - A basic enemy's Attack is the SDK's, unrounded. The SDK floors it, but
//   unrounded it is exactly what the game shows (1.18, 1.39, 2.30, 3.56 and
//   15.90 on waves 1, 2, 5, 8 and 22 of the owner's screens).
// - A basic enemy's health is the SDK's, unrounded, times a correction fitted
//   to the owner's screens: the SDK runs high by about half a percent a wave.
//   The fit is only known to wave 22, so it holds at wave 22's value past it.
//   Replace it when a later wave is read.
// - Type multipliers, speeds and masses are the SDK's (mass sets how far
//   Knockback pushes). The type mix is the owner's
//   wave 22 screen, which disagrees with the SDK's 91/3/3/3.
// - Wave timing is the SDK's: 26 seconds of spawning, then a cooldown.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import Module from "node:module";

const LAST_WAVE = 6500;
const HEALTH_DRIFT_PER_WAVE = 0.9953;
const HEALTH_DRIFT_KNOWN_TO = 22;
// The owner's screens, Tier 1, 24 and 25 September 2026.
const READINGS = [
  { wave: 1, health: 2.35, attack: 1.18 },
  { wave: 2, health: 3.31, attack: 1.39 },
  { wave: 5, health: 7.2, attack: 2.3 },
  { wave: 8, health: 12.15, attack: 3.56 },
  { wave: 22, health: 63.11, attack: 15.9 },
];
const MIX = { basic: 0.85, fast: 0.07, tank: 0.06, ranged: 0.02 };

const sdkRoot = path.resolve(process.argv[2] ?? "package");
const require = createRequire(path.join(sdkRoot, "package.json"));
const dist = path.join(sdkRoot, "dist");

// The SDK floors Attack inside a function it doesn't export unrounded, so
// load that one module with the floor taken out.
function loadUnroundedScaling() {
  const file = path.join(dist, "mechanics/waves/base-empirical-scaling.js");
  const source = fs.readFileSync(file, "utf8");
  const floored = "    const raw = envelope * linearTerm * centuryStack * damageTierAttenuationFactor(t, tierPressure);\n    return Math.floor(raw);";
  if (source.split(floored).length !== 2) {
    throw new Error("computeEmpiricalWaveBaseDamage has changed shape; check the SDK version");
  }
  const mod = new Module(file);
  mod.filename = file;
  mod.paths = Module._nodeModulePaths(path.dirname(file));
  mod._compile(source.replace(floored, floored.replace("Math.floor(raw)", "raw")), file);
  return mod.exports;
}

const scaling = loadUnroundedScaling();
const panel = require(path.join(dist, "mechanics/waves/info-panel-stats.js"));
const uptime = require(path.join(dist, "mechanics/uptime/compute.js"));
const typeMults = require(path.join(dist, "mechanics/enemies/type-mults.js")).ENEMY_MULT_BY_TYPE_TABLE;

const healthDrift = (wave) => HEALTH_DRIFT_PER_WAVE ** (Math.min(wave, HEALTH_DRIFT_KNOWN_TO) - 1);
const input = (wave) => ({ wave, tier: 1, tournament: false });
const keep = (value) => Number(value.toPrecision(9));

const health = [];
const attack = [];
const speed = [];
for (let wave = 1; wave <= LAST_WAVE; wave++) {
  health.push(keep(scaling.computeWaveBaseHealthRaw(input(wave)) * healthDrift(wave)));
  attack.push(keep(scaling.computeWaveBaseDamage(input(wave))));
  speed.push(keep(panel.computeWaveInfoPanelEnemyExtras({ ...input(wave), enemyType: "Basic" }).speed));
}

// Two decimals is what the screen shows; allow the last one either way.
for (const reading of READINGS) {
  const got = { health: health[reading.wave - 1], attack: attack[reading.wave - 1] };
  for (const stat of ["health", "attack"]) {
    if (Math.abs(got[stat] - reading[stat]) > Math.max(0.011, reading[stat] * 0.003)) {
      throw new Error(`wave ${reading.wave} ${stat}: generated ${got[stat]}, screen ${reading[stat]}`);
    }
  }
}

const types = {};
for (const [id, name] of [["basic", "Basic"], ["fast", "Fast"], ["tank", "Tank"], ["ranged", "Ranged"], ["boss", "Boss"]]) {
  const typeSpeed = panel.computeWaveInfoPanelEnemyExtras({ ...input(1), enemyType: name }).speed;
  const mass = panel.computeWaveInfoPanelEnemyExtras({ ...input(1), enemyType: name }).mass;
  types[id] = { health: typeMults[name].hp, attack: typeMults[name].damage, speed: keep(typeSpeed), mass: keep(mass) };
}

const out = {
  version: 1,
  source: "The Tower's Tier 1 enemies via TheTowerSDK 0.11.0 (MIT, TmRxJD), calibrated to the owner's screens. Generated by tools/import_tower_enemies.mjs.",
  readings: READINGS,
  health_drift: { per_wave: HEALTH_DRIFT_PER_WAVE, known_to_wave: HEALTH_DRIFT_KNOWN_TO },
  spawn_seconds: uptime.computeWaveCombatDurationSeconds(false),
  cooldown_seconds: keep(uptime.computeWaveInterCooldownSeconds(0, { tournament: false })),
  boss_every: 10,
  mix: MIX,
  types,
  basic_health: health,
  basic_attack: attack,
  basic_speed: speed,
};
const outPath = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "data", "tower", "enemies.json");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(out) + "\n");
console.log(`wrote ${LAST_WAVE} waves to ${path.relative(process.cwd(), outPath)}`);
for (const r of READINGS) {
  console.log(`wave ${r.wave}: health ${health[r.wave - 1]} (screen ${r.health}), attack ${attack[r.wave - 1]} (screen ${r.attack})`);
}
